openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /status:
    get:
      summary: Health check endpoint
      description: Returns the current status of the API
      operationId: getStatus
      tags:
        - Health
      responses:
        '200':
          description: API is healthy and operational
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Current status of the API
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-10-16T12:00:00Z'
                    description: Current server timestamp
                required:
                  - status

